version: '3.2'

services:
  db:
    image: mysql:5.7.32
    platform: linux/x86_64
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  mysql-datavolume:
    driver: local